#!/usr/bin/env bash

###
# uniqList [-f] <delimited string> [delimiter]
#
# Takes a delimited string and returns a delimited with only the unique elements
# from the origingal string.
#
# Flags:
# -f  case insensitive
# Positional Arguments:
# $1  delimited string
# $2  delimiter (default: ',')
# 
# Example:
# uniqList -f "World hello world" " "
# ->  hello world
#
# uniqList "cats,dogs,birds,cats"
# ->  birds,cats,dogs
###

# Initialize variables
delim=','
str=''
sort_options='-u'

# Check for at least 1 argument
[ "$#" -lt 1 ] && exit 1

# If flag is set, then change the sort options
[ "$1" == "-f" ] && { sort_options="-u -f"; shift; }

# Is the string argument set?
[ -z "$1" ] && exit 1
str="$1"

# If delimiter is specified, then set it
[ -z "$2" ] || delim="$2"

# The heart of this is the 'sort -u' part. It sorts the items and only leaves
# unique elements. The ending 'sed' removes the delimiter that may appear at the
# front or end of the string.
str=$(echo "$str" | tr "$delim" '\n' | sort $sort_options | tr '\n' "$delim" | sed -e "s/$delim$//" -e "s/^$delim//")

# Echo the new delimited list
echo "$str"

exit 0